name: LateX to PDF

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches: [master]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: latex2pdf
        id: compile-latex-document
        uses: thomas-chauvet/latex2pdf-action@1.0.1
        with:
          output_dir: output
          main_latex_file: book/book.tex
          ctan_packages: mathpazo
      - name: Upload PDF to the workflow tab
        id: upload-workflow-tab
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output/test.pdf
